"""Initial_db

Revision ID: ad1f38146b4d
Revises: 
Create Date: 2020-11-02 12:38:27.798632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1f38146b4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constellation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('abbr', sa.String(), nullable=True),
    sa.Column('english_name', sa.String(), nullable=True),
    sa.Column('pronunciation', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('star',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('bayer_designation', sa.String(), nullable=True),
    sa.Column('right_ascension', sa.String(), nullable=True),
    sa.Column('declination', sa.String(), nullable=True),
    sa.Column('apparent_magnitude', sa.String(), nullable=True),
    sa.Column('absolute_magnitude', sa.String(), nullable=True),
    sa.Column('distance', sa.String(), nullable=True),
    sa.Column('constellation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['constellation_id'], ['constellation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('star')
    op.drop_table('constellation')
    # ### end Alembic commands ###
